spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample_email
    username: uwaas
    password: 1qazxsw2
    pool:
      validation-query: SELECT 1
    properties:
      lock_timeout: 40000
      statement_timeout: 40000
      idle_in_transaction_session_timeout: 40000
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 12500